### ISSUE TITLE
[PROMENADE] : haricots affichés dans les 2 parcelles

### ISSUE THREAD

**Issue by neobast** [neobast/potager#10]
Feature parcours : j'ai mes haricots qui sont passés de la parcelle balcon à la parcelle L2. Mais du coup ils s'affichent dans les deux. Je pense qu'il faudrait rajouter une condition et ne prendre en compte que la dernière localisation.

**Comment by neobast** [comment]
Arf oui mais là on a un souci.. j'ai deux étapes semis séparées... Donc la c'est plutot un usecase pas prévu..
Hum... il faut que l'on revoit ca

**Comment by magictex33** [comment]
Ok je comprends. On part alors du principe que le terme parcelle ne peut pas être utilisé comme emplacement temporaire, c'est définitif - ce qui est logique.
Du coup on préfèrera utiliser le label/contenant.
Si tu es ok je pense que l'issue peut être fermée.

**Comment by neobast** [comment]
Ok. Je cloture du coup.

**Comment by neobast** [comment]
N'afficher qu'une seule etapesemis par parcelle (exemple laitue sucrine sur balcon pour @magictex33 )
