### ISSUE TITLE
[Semence] Filtre sur la page d'index

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#100]
Il serait pertinent de pouvoir effectuer un flitre par catégorie (aromatique, légume feuille etc.) comme spécifié dans les références pour limiter l'affichage à cette catégorie.

**Comment by neobast** [comment]
@magictex33 : besoin de précision stp 
Pas de souci pour trier par catégorie. Mais en gros, tu veux pouvoir definir dans les préférences les categories que tu veux voir afficher c ca ? ou est ce que tu veux pouvoir trier l'affichage des semens en sélectionnant (ex checkbox ? )

**Comment by neobast** [comment]
@magictex33 : est ce qu'une recherche en mode tableau répondrait à ton besoin ? commes le familles par exemple ?

**Comment by magictex33** [comment]
Alouter un dropdown avec les différentes catégories serait une bonne solution je pense.

**Comment by magictex33** [comment]
L'implémentation actuelle répond au besoin. Je cloture.
