### ISSUE TITLE
[Planification] Visualisation étape planification

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#104]
Afin de rester cohérents avec le reste de l'application, il me semble pertinent de :
- ne pas afficher une étape semis de catégorie planification dans la page promenade
- affichir une étape semis de catégorie planification dans la page qui liste toutes les étapes de la semence correspondante

**Comment by neobast** [comment]
J'ai fait la première partie de la story. 
Pour le deuxième, c'est la semence ou le semis ? parce que pour le semis, j'ai toujours les étapes qui sont affichées.

**Comment by magictex33** [comment]
- Regarde la 105 pour ce qui concerne l'ordre d'affichage
- maintenant l'affichage dans semis n'est plus ok, les éléments FDS sont à nouveau affichés

**Comment by neobast** [comment]
Arf... vu le souci des FDS. My bad. Je vais regarder

**Comment by magictex33** [comment]
Je relance cette issue. Pour moi la visualisation n'est pas optimale. Idéalement tri par parcelle PUIS par l'espèce la plus précoce etc.

**Comment by neobast** [comment]
J'ai calqué l'affichage sur la 105.
104 : "déalement tri par parcelle PUIS par l'espèce la plus précoce  " => ok pour prendre en compte la date récolte mais je merde sur l'affichage car si j'ai 2 parcelles, elles s'affichent à la suite (cf 105)
Tant que je serai pas en react, je bidouille

**Comment by magictex33** [comment]
Tes dernières modifs sont nickel. Je cloture.
