### ISSUE TITLE
[Semence] Ajout d'un champ commentaire

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#108]
Dans certains cas, un user souhaite ajouter des éléments qui ne doivent pas être indexés et qui ne servent pas dans le reste de l'application.
Ex. : planter en poquets de 4 graines dans des mottes de 4x4

Le champ serait lié à une semence ET à un user (l'info est individuelle)

**Comment by neobast** [comment]
Pas de souci.  Mais tu veux l'afficher ou ce commentaire? 
Parce que si c au niveau de la semences 
Commence a me dire que la semence va devenir individuelle ..
Je pense aux durées de recolte, duree de  croissance, temperature de germination qui en fait sont fortement liées a l'utilisateur (a la région en fait)

**Comment by magictex33** [comment]
Oui oui, c'ist bien lié à la semence, tout comme les paramètres que tu indiques c'est bien pour un user.

**Comment by magictex33** [comment]
Parfait !
