### ISSUE TITLE
[Accueil] Lien rapide vers un semis

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#112]
Sur la page d'accueil, apparaissent les semences du mois. Actuellement en cliquant sur le lien on arrive sur la page semence.
Il serait intéressant de pouvoir déclencher directement une étape semis avec ce lien.

**Comment by neobast** [comment]
Pour déclencher une étape semis, il faut que le semis existe. 
Du coup, je peux pas déclencher directement une etape semis. Il faut d'abord créer un semis. 
ensuite, il faudrait que je verifie que l'on a bien la semence en stock. Histoire de pas créer un semis avec un semence qu je en'ai pas

**Comment by magictex33** [comment]
OK. Même remarque que là https://github.com/neobast/potager/issues/113#issuecomment-782826080
Ce que tu proposes, la vérification du stock, ers une étape supplémentaire.
Je propose : 
- On clique sur le lien
- Vérification du stock, si nul alerte et abandon (dans une future étape, lien vers la création ?)
- Si stock alors menu de sélection de la saison avec Semence présélectionnée

**Comment by magictex33** [comment]
Ok pour moi
