### ISSUE TITLE
[Semence] Ajout d'un bouton étape semis

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#113]
À partir du détail d'une semence (/semence/show/67 par exemple) il serait intéressant d'ajouter un bouton permettant d'ajouter directement une étape semis.

**Comment by neobast** [comment]
L'étapesemis est liée à un semis (lié lui même à une saison et une semence). 
Quid si tu crées 2 semis depuis la semence Basilic par exemple ? vers laquelle des étapesemis j'ajoute ?

**Comment by magictex33** [comment]
Ca ne me pose pas de problème qu'on arrive sur le menu ci-dessous, idéalement avec une présélection sur la semence.

![Screenshot from 2021-02-21 10-22-38](https://user-images.githubusercontent.com/67335206/108620792-c0fc2600-742e-11eb-83e0-409044355155.png)

**Comment by neobast** [comment]
@magictex33  Hummm... j'ai comme qui dirait envie de tt créer sans rien sélectionner. Parce que la semence, on l'a. Et la saison, bin on l'a aussi... Qu'en penses tu ?

**Comment by neobast** [comment]
Si je continue dans cette voie la on arrive à la 112. Bon là j'ai pas vérifier si on avait du stock dans l'affichage .

**Comment by magictex33** [comment]
Ah oui oui, si c'est possible c'est encore mieux

**Comment by magictex33** [comment]
Ok pour moi
