### ISSUE TITLE
[Planification] : Retro planning a partir d'une date de recolte souhaitée

### ISSUE THREAD

**Issue by neobast** [neobast/potager#116]
Si l'utilisateur renseigne une date de récolte, le tableau des prévision doit en tenir compte et doit calculer automatiquement la date action.

**Comment by neobast** [comment]
@magictex33 Bien évidemment si il n'y a pas de durée pépiner, recolte et croissance, la modification ne servira pas à grand chose

**Comment by magictex33** [comment]
Ok par rapport au fonctionnement. Par contre je pense qu'il ne faudrait pas afficher par défaut une date de récolte lors de la création d'une étape semis.

**Comment by magictex33** [comment]
OK pour moi
