### ISSUE TITLE
[Semence] Non affichage des étapes semis

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#117]
Lors de l'affichage du détail d'une semence (/semis/show/129) le détail des étapes semis était affiché sur la page. Ce n'est plus le cas.
Il est donc impossible de modifier ou supprimer un état semis associé.

**Comment by neobast** [comment]
Hum.. je n'ai rien fait de spécial concernant l'affichage des semis . Je n'ai pas de règle. Par contre pour l'artichaut, j'ai vu que tu as un autre semis qui lui est rempli /semis/show/117 (qui lui fonctionne très bien)
Et j'ai remarqué la même chose pour /semis/show/112.
J'ai vu cela depuis la page semis index. Je soupconne que ce soit des erreurs lors de mes deploiements de création semis...

**Comment by magictex33** [comment]
Oui oui. Suis en phase, pas d'erreur c'est moi qui l'ai crée. Mais comment je fais pour modifier ou supprimer mon semis artichaut qui est vide du coup ?
Je pense qu'on pourrait avoir toutes les étapes semis associées à la semence sous la semence pour l'éditer ou.supérimer.

**Comment by magictex33** [comment]
Bug sur un élément précis, non reproductible. Je cloture.
