### ISSUE TITLE
[ETAPESEMIS] : Suppression de quantite et poids

### ISSUE THREAD

**Issue by neobast** [neobast/potager#118]
Nous utilisons à la fois quantité et nombre. Je pense que quantité et poids sont issus de la v0 et ne sont plus utilisés au niveau de l'étape semis mais du  stocks. 
Je propose : 

- [ ] suppression du champ poids (il est déjà vide pour toutes les étapesemis créées)
- [ ] copie des valeurs de quantité vers nombre (si nombre vide) puis suppression du champ quantité.

Qu'en penses tu ?

**Comment by magictex33** [comment]
Tout à fait d'accord avec.toi !

**Comment by magictex33** [comment]
Parfait
