### ISSUE TITLE
[Semis] Pas d'affichage des durées

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#121]
Le nouvel affichage des semis comporte une erreur : aucun affichage des durées (pépinière, croissance, récolte).

**Comment by neobast** [comment]
normalement, il y a un bouton cloud juste en dessous des chiffres permettant de récupérer les données de la semence. 
Je peux aussi faire en sorte que les données soient récupérées pour tous les semis en cours

**Comment by neobast** [comment]
je vais peut être le grossir du coup

**Comment by magictex33** [comment]
Ok. Je ne l'avais pas. Parfait pour moi, je cloture
