### ISSUE TITLE
[Semis] Affichage de l'Id semis

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#122]
L'Id semis est parfois utilisé comme identifiant pour une plaque ou une série de godets. Il serait utile de l'afficher dans une colonne lors de l'affichage de toutes les étapes semis.

**Comment by magictex33** [comment]
Non. Tu affiches l'id de l'étape semis alors qu'il faudrait afficher l'id du semis correspondant.

**Comment by neobast** [comment]
Ok. Mais du coup, je trouve pas ça logique. Afficher l'ID semis dans la page semis... hummmm... 
Je fais la modification et tu me diras.

**Comment by magictex33** [comment]
Je trouve ca pas mal comme ca, c'est effectivement l'info qu'il me faut. Par contre suis d'accord sur la pertinence de le répéter à chaque ligne. Peut etre plus intéressant de le mettre ailleurs. On en rediscute.

**Comment by magictex33** [comment]
J'ai regardé par rapport à ton commentaire, ce que je te propose : 
- supprimer la colonne Id Semis dans les étapes
- ajouter l'Id Semis dans le titre. Exemple : « Semis 147 - Été 2021 »

**Comment by magictex33** [comment]
Yes, parfait !
