### ISSUE TITLE
[Semence][Semis] Ordre des éléments box de gauche

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#135]
Dans la box de gauche, il serait pertinent d'afficher les éléments dans un autre ordre, comme dans un tableau 2 lignes / 3 colonnes.
- 1ère ligne / 1ère colonne : exposition
- 1ère ligne / 2ème colonne : annuel ou vivace etc
- 1ère ligne / 3ème colonne : température germination ( mettre « - » si non disponible)
- 2ème ligne / 1ère colonne : besoin en eau
- 2ème ligne / 2ème colonne : graines / gramme
- 2ème ligne / 3ème colonne : température germination

**Comment by neobast** [comment]
1ère ligne / 3ème colonne : température germination ( mettre « - » si non disponible) et 
2ème ligne / 3ème colonne : température germination
Du coup on pourrait mettre "temperature de croissance ? " plutot ?

**Comment by magictex33** [comment]
La température de croissance est subjective alors que pour la germination il faut une température minimum.

**Comment by magictex33** [comment]
Perfekt !
