### ISSUE TITLE
[Plante] Ajout d'un commentaire

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#139]
Pour un grand nombre de variétés, le commentaire est commun à toutes les variétés. Permettre l'ajout de celui-ci au niveau de la plante.
- Chaque commentaire est lié à une plante ET à un utilisateur
- La représentation est : commentaire plante, retour à la ligne, commentaire espèce (pas de changement pour le commentaire étape semis)

**Comment by neobast** [comment]
Par contre je veux bien que tu me dises ou tu veux que je positionne le commentaire de la plante sur la page semence ou semis ?

**Comment by magictex33** [comment]
Au meme endroit que les autres commentaires, dans la box de gaeche. Je l'ai précisé dans l'issue 😋

**Comment by neobast** [comment]
Modifié

**Comment by magictex33** [comment]
Par contre vu que tu as mis un "+" je pense qu'il faut généraliser. 
Donc "+" quand il n'y a pas de commentaire et l'icone éditer quand il y en a un et qu'on peut l'éditer.

Par contre il ne me semble pas pertinent de pouvoir supprimer le commentaire de la plante depuis un autre endroit que la page plante. Mais à rediscuter.

**Comment by neobast** [comment]
Suite à discussions de ce matin : 
- pas d'édition de l'info Plante hors de la page plante : ok
- quid de la création ? est ce que je laisse un bouton pour créer une info plante depus la semence et le semis  ?

**Comment by magictex33** [comment]
Non. Avec le lien vers semence/plante il est facile d'y aller pour le créer et ca permet de bien faire le distingo.

**Comment by magictex33** [comment]
Parfait
