### ISSUE TITLE
[PARCELLE][SHOW] : Erreur quand un semis a plusieurs parcelles

### ISSUE THREAD

**Issue by neobast** [neobast/potager#144]
Lors de l'affichage d'une parcelle, si une étape semis a plusieurs parcelles, l'affichage d'une parcelle montre autant d'étapes semis qu'il y a de parcelles. 
Alors qu'il devrait y avoir qu'une seule ligne

**Comment by neobast** [comment]
parcelle/showplanification/15

**Comment by magictex33** [comment]
Yes, je ferme
