### ISSUE TITLE
[SEMENCE][SHOW] : Affichage des parcelles dans la prévision

### ISSUE THREAD

**Issue by neobast** [neobast/potager#145]
Dans le tableau des prévisions, il n'est pas possible de cliquer sur une parcelle pour voir ce qu'elle contient. 
Soit on met un lien pour aller sur la page, soit il faut que qqchose s'affiche pour indiquer à l'utilisateur
ce qu'il a sur cette parcelle.

**Comment by magictex33** [comment]
Ok pour moi
