### ISSUE TITLE
[SEMENCE] : Permettre un ajout de photo

### ISSUE THREAD

**Issue by neobast** [neobast/potager#22]
En tant qu'utilisateur de l'application
je souhaite pouvoir ajouter une ou plusieurs photo de la semence (ex: le sachet, une photo de ma plante)
afin de pouvoir avoir un affichage plus sympa

**Comment by neobast** [comment]
Version 1 faite pour les étapes. Reste pour les semences.

**Comment by magictex33** [comment]
Ok pour moi je propose de cloturer
