### ISSUE TITLE
[SEMENCE][INDEX] : Revoir l'affichage de la liste

### ISSUE THREAD

**Issue by neobast** [neobast/potager#24]
Petit à petit, l'affichage commence à être de plus en plus grand...
Il faut revoir l'affichage.
tri par type : Legume-Fruit/Legume-Feuille/Legume-Racine ?

**Comment by neobast** [comment]
Sinon Potagère, Fleurs, Aromatiques, Engrais verts ?

**Comment by magictex33** [comment]
Une fusion des deux ? Parce que dans tous les cas l'affichage des légumes seuls explosera l'affichage.

**Comment by neobast** [comment]
Oui une fusion des deux. A discuter de vive voix pour definir tout ca.

**Comment by neobast** [comment]
Affichage modifié. Qu'en penses tu ?

**Comment by neobast** [comment]
@magictex33 up

**Comment by magictex33** [comment]
Ah pas vu l'issue. Oui, parfait pour moi.
