### ISSUE TITLE
[TERREAU] : Permettre de créer des terreaux user only ?

### ISSUE THREAD

**Issue by neobast** [neobast/potager#26]
Autant avoir les avis sur les terreaux génériques, c'est pas mal, autant avoir l'avis sur le terreau d'un autre utilisateur n'est pas forcément pertinent.
A voir...
Pas sur que ce soit forcement la fonctionnalité ultime

**Comment by magictex33** [comment]
Si on met en relation avec la #25 cela me parait super pertinent de le lier à un utilisateur.

**Comment by neobast** [comment]
Ok.
Nouveaux champs pour terreau :
- "mode" (option à cocher lors de la création) : 
  - mode public 
  - mode user-only (dans ce cas, c juste pour l'utilistateur. l'admin aura accès à tout)
- "prix" optionnel (pratique pour la grande distrib)
- "volume" : Qd c 40L ou 50L 
- "date de mise à jour" (transparent pour l'utilisateur)
- "commentaires" : optionnel pour tout le monde

**Comment by magictex33** [comment]
Ok pour moi.
Pas besoin de m'affecter systématiquement TES issues 😁
