### ISSUE TITLE
[Promenade] Affichage du dernier état

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#27]
Dans le mode promenade, tout les éléments sont affichées alors qu'un filtre doit être fait :
- si il y a juste un élément plantation alors il doit être affiché
- dans le cadre d'une remarque, bien qu'elle soit saisie dans ce mode, si elle n'est pas associée à une parcelle elle ne s'affiche pas. Si elle est associée, alors ca doit être le dernier élément à s'afficher.

Je pense qu.on doit refaire un point sur ce qui est affiché et quand.

![Screenshot_20200728-060521](https://user-images.githubusercontent.com/67335206/88620336-070e2880-d09e-11ea-8e5b-a88692a9ba80.png)

**Comment by neobast** [comment]
Cloture car résolue par la #48
