### ISSUE TITLE
[Promenade] Ajout de photo

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#29]
Dans le mode promenade il est possible d'ajouter un état "Remarque". Il serait pertinent de pouvoir y associer une photo.

**Comment by magictex33** [comment]
Ok pour toi @neobast si on cale ca pour la v1 ?

**Comment by neobast** [comment]
ok pour moi @magictex33

**Comment by neobast** [comment]
Du coup, ca veut dire qu'on va rajouter une Photo à une étapeSemis en fait.
L'idée est bien de pouvoir rajouter une photo à une étape Semis ?

**Comment by magictex33** [comment]
Oui c'est ca.
- On ajoute un commentaire en mode promenade ou une remarque en étape semis
- En meme temps que le champ commentaire, on a un champ photo pour faire un upload
- En plus de l'onglet Étapes dans l'index onqpourrait avoir un onglet Photo avec la galerie photo correspondante (nouvelle feature pour la v1.2)
