### ISSUE TITLE
[Feature] Fiche plante/semis

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#30]
En fin de saison il serait pertinent de pouvoir regrouper tous les commentaires sur un semis en fonction des parcelles. Peut-etre sur la page semis d'une plante spécifique ?

**Comment by neobast** [comment]
Je vois un peu ce que tu veux dire, mais faut une discussion de vive voix et un exemple. 
Mais je me m'étais fait la même reflexion sur le fait que je voudrais capitaliser les infos en fin de saisons..
Une fois que le semis est terminé, il passe en archive. 
Le regroupement de commentaire (avec la parcelle concernée) cloturait le passage en archive

**Comment by magictex33** [comment]
Oui. Trés bien la notion de passage en archive 👍

**Comment by neobast** [comment]
Clôture car archivage fonctionne désormais
