### ISSUE TITLE
[SEMENCE] : Suppression de paramètres

### ISSUE THREAD

**Issue by neobast** [neobast/potager#32]
Suite discussion, il serait judicieux de supprimer %germination et nombre ? 
Au départ le nombre était surtout pour gérer un eventuel stock par utilsateur. Pb : Soit c au poids soit c au nombre de graine...
Pas top top 
Quand a pourcentage germination.. c le paramètre indiqué par kokopelli sur le sachet.. pertinent ?

**Comment by magictex33** [comment]
Suis du meme avis pour le supprimer. Idéalement on pourrait plutot l'ajouter comme étape semis : la germination réelle.
