### ISSUE TITLE
[SEMENCE] : Grimpant ?

### ISSUE THREAD

**Issue by neobast** [neobast/potager#33]
Grimpant est pertinent pour les haricots et le variétés qui montent..
Mais celles qui sont coureuses comme les melons ou les courges ? 
Rajoute-t-on un paramèter coureuse ? ou dis-t-on que grimpant peut être renommer en grimpant/coureur ?

**Comment by magictex33** [comment]
Les melons ou les courges peuvent etre palissés aussi (bon, plus les courges). Peut-etre doit on plus insister sur le type d'implantation que l'on peut faire que sur la nature elle-meme de la plante ?

**Comment by neobast** [comment]
Effectivement, c plus un type d'implantation qu'une caractéristique de la plante.
De fait, ce paramètre est pas forcément nécessaire. Apparaitra dans les commentaires du coup ?

**Comment by magictex33** [comment]
Si on veut pouvoir faire un tri dessus à l'avenir il doit etre dans un champ identifié.

**Comment by neobast** [comment]
Proposition 
champ implantation avec comme choix : 
- coureuse (par defaut)
- palissé 
- grimpant

**Comment by magictex33** [comment]
Ok pour moi, avec la valeur vide aussi

**Comment by neobast** [comment]
Ok pour toi  ?

**Comment by magictex33** [comment]
Oui, ta proposition me va. Tu n'as pas encemore fait les modifs, si ?

**Comment by neobast** [comment]
Non pas encore fait. J'ai juste un grimpant avec Oui/Non. 
Donc je vais faire comme tu le suggérais : 
Implantation avec comme choix :

    coureuse (par defaut)
    palissé
    grimpant

Est ce que je fais en sorte qu'on puisse rajouter des catégories d'implantations à l'avenir ou pas ?

**Comment by magictex33** [comment]
Ca pourrait etre pas mal, comme ca on ne sera pas bloqué.

**Comment by neobast** [comment]
@magictex33 up

**Comment by magictex33** [comment]
Parfait pour moi je cloture.
