### ISSUE TITLE
[SEMENCE] : Modification affichage de l'index

### ISSUE THREAD

**Issue by neobast** [neobast/potager#36]
Sur la page de l'index, le fait d'afficher autant de modal pour permettre l'édition et la suppression va causer des ralentissement à terme.
Je propose qu'on enlève ces icones sur la page.
Si besoin on clique sur la semence et on l'édite. Pas possible de la supprimer (pas de lien mais fonctionnalité existante)

**Comment by magictex33** [comment]
Oui pas de pb.

**Comment by neobast** [comment]
Done. Je cloture.
