### ISSUE TITLE
[Semence] Gestion de stock individuel

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#37]
La gestion de stock mérite à mon avis d'etre revue en plus d'etre gérée individuellement : 
ton stock ne correspond pas au mien.

À mon avis dans un premier temps une bete case à cocher oui/non serait suffisante.

Un filtre sur les éléments en stock serait pertinent sur la page plantes.

**Comment by neobast** [comment]
Mais du coup, la semence, tu souhaites qu'elle soit liée à un utilisateur ? Parce que la, telle que je le fais, ce sera non pour cette story.
Si oui, je dois prévoir d'avoir cette notion d'utilisateur au niveau de la semence. Mais dans ce cas, il faut qu'on modifier la story.

**Comment by neobast** [comment]
Travail pas compliqué à faire sachant uque je l'ai déjà fait pour Semis

**Comment by magictex33** [comment]
Non, je pense qu'il doit juste avoir un booleen supplémentaire Stock rattaché à un user.
