### ISSUE TITLE
[Semis] Pas de comentaire affiché pour récolte

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#38]
Dans le cadre de la saisie d'un commentaire en meme temps qu'un état récolte, il n'est pas affiché dans le tableau récap de l'index.

**Comment by neobast** [comment]
Hum..
Je n'arrive pas à reproduire le bug... Tu parles de l'index des semis c'est ca ? Si c'est le cas, c'est seulement le dernier état qui est affiché (et non le dernier etat modifié).
Mais ca peut se modifier

**Comment by magictex33** [comment]
Ah faut qu'on voit ensemble mais maintenant ca fonctionne. Peut etre unqpetit bug quand j'étais dessus.

**Comment by magictex33** [comment]
Vu ensemble, je cloture.
