### ISSUE TITLE
[Aspect général] Couleur du thème

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#41]
L'application à une vocation « nature », généralement identifiée par des palettes de couleur tendant sur le vert.
Ne serait-il pas plust pertinent de changer le thème du bootstrap (actuellement bleu) pour le faire tendre vers qque chose de plus orienté « vert » ?
Ex :
- https://themeforest.net/item/green-soul-environment-nonprofit-html-template/19612213
- https://themeforest.net/item/greenforest-environmental-ecology-responsive-template/19671308
- https://themeforest.net/item/greenture-environment-nonprofit-html-template/15637784

On pourrait ensuite associer ce même thème au site internet :-)

**Comment by magictex33** [comment]
Celle-là est ok pour moi, on pourrait la cloturer si tu es ok

**Comment by neobast** [comment]
ok aussi
