### ISSUE TITLE
[Stock] Faciliter la lecture avec des icônes

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#43]
En lien avec #42 

Afin de faciliter la lecture sur la page d'index, je propose l'association d'icones au type de quantité :

- Nombre : https://fontawesome.com/icons/tablets?style=solid
- Poids : https://fontawesome.com/icons/balance-scale-right?style=solid
- Sachet : https://fontawesome.com/icons/envelope?style=solid

**Comment by neobast** [comment]
Icones ajoutées

**Comment by magictex33** [comment]
J'ai réouvert juste pour associer la lettre "g" à droite de la mesure quand l'unité est le gramme.
Ex. 10 icone => 10 g icone
