### ISSUE TITLE
[Global] Fin de saison / Archivage

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#44]
Principe général : un semis suit un workflow, avec ses différents états, depuis l'état de « semis sous abri / en place / etc.» jusqu'à la fin de vie de l'élément qui a poussé et a donné des récoltes. Il faut pouvoir archiver le workflow afin qu'il puisse être interprété pour le retour d'expérience avant un nouveau.

Notas :
- Le workflow est spécifique à une plante donnée et se déroule sus sa propre chronologie
- Un état FDS - Fin de saison existe déjà dans la liste

**Comment by magictex33** [comment]
Si l'état FDS existe, dans un premier temps on pourrait :
- Ne plus afficher les étapes associées à l'étape qui est en FDS. Peut etre avec un champ supp FDS et la date à laquelle on a passé en FDS
- Pouvoir afficher, cette fois ci en mode quadrillage, tous les semis/étapes sur une période donnée

**Comment by neobast** [comment]
Besoin validation client

**Comment by magictex33** [comment]
Tu peux me préciser ce que je dois valider exactement par rapport aux éléments déjà en place ?
Au passage, le modal d'archivage ne s'affiche plus.

**Comment by neobast** [comment]
me souviens plus de ce que j'avais fait...
En gros, on avait dit quoi ? qu'on passait par le profile pour archivers tous les semis ?
LA en regardant ton profil, tes semis sont pas liés à une saison..

**Comment by magictex33** [comment]
Oui. Ai fait le parcours utilisateur. Pour moi tout est ok.

**Comment by neobast** [comment]
En fait, je viens de comprendre. SI j'ai des états semis en FDS et qu'ils nont pas de saison associés, alors on les voit dans le bouton Archiver au niveau des saisons du profile.

Et il manque le cas ou il y a un etat FDS et  une saison definie (ex: tes radis que tu as crée aujourd'hui). Dans ce cas là, je pourrais rajouter un bouton archivage au niveau du semis ?

**Comment by magictex33** [comment]
Ah je ne comprenais pas pquoi je ne pouvais pas les archiver.
OK pour rajouter un bouton, mais visible uniquement quand on est dans l'état FDS

**Comment by magictex33** [comment]
OK pour moi
