### ISSUE TITLE
[Semence] Gestion des doublons

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#45]
Comment doit-on gérer les doublons ?
Ex. lavande en doublon (lavande officinale / lavande vraie).

**Comment by magictex33** [comment]
Sera abordé lors d'un PE

**Comment by magictex33** [comment]
Ben du coup pourquoi c'est fermé ? 🙄

**Comment by neobast** [comment]
Parce que jai vu le souci pour le stock.. et du coup quand jai vu la demande poir semence quasi identique😋
A rediscuter bien évidemment !!!

**Comment by neobast** [comment]
En gros mon commit a clôturé l'issue 😅

**Comment by neobast** [comment]
Résolu avec #63
