### ISSUE TITLE
[Plantation] Régression - Affichage du dernier état

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#48]
Ce n'est pas la dernière étape qui s'affiche dans la page, idem #27 
Ex. Carré 2 / Roma paste : il devrait il y avoir la remarque et non plantation.

**Comment by neobast** [comment]
@magictex33 : après recherche, il s'avère que l'étape "REmarque" rajoutée ne comporte pas de Parcelles. 
Tu as du la rajouter en dehors du mode promenade car celui-ci positionne directement la parcelle. 

25/07/2020       Maj | Remarque |   |   | Belles tomates encore vertes sur des grappes. Plants de 2m
-- | -- | -- | -- | --

**Comment by magictex33** [comment]
OK vu. Pourtant cela s'affichait bien avant. Au moins on a vérifié.
Je cloture.
