### ISSUE TITLE
[Semis] Étape semis - Champ fichier vide après ajout photo

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#50]
Dans le modal d'ajout d'une étape semis, après ajout d'une photo via le bouton parcourir, aucun nom ou chemin n'apparait dans le champ correspondant.
- faire en sorte que le champ indique le nom du fichier
- ou le remplacer par un indicateur permettant de voir si un fichier a déjà été choisi

**Comment by neobast** [comment]
http://90.3.181.176/etapesemis/add/52

**Comment by neobast** [comment]
et visiblement, n'a pas l'air de marcher quand on édite une étape.. a voir

**Comment by neobast** [comment]
bUG BOOTSTRAP.
