### ISSUE TITLE
[Données] Chou

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#52]
J'ai un problème avec semence/show/23 que tu as saisi @neobast .

Pour moi ca devrait être : 
- Plante : chou
- Variété : de Milan - Westlandse Putjes

Problématique survenue à l'ajout de : Chou - brocoli vert calabrais

**Comment by magictex33** [comment]
Sera abordé lors d'un PE

**Comment by neobast** [comment]
Validé en PE que la modification peut être effectuée sur la plante. Cela n'impacte pas les enregistrements car référence par Id

**Comment by neobast** [comment]
Corrigé
