### ISSUE TITLE
[Stock] Auhentification pour suppression

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#54]
Lors de la suppression d'une entrée stock (pour la 23), renvoi systématique vers la page de connexion puis vers la page d'erreur lors de la tentative suivante.

**Comment by neobast** [comment]
L'application github eqt nulle.. sur l'aperçu tu vois que jai fait un commit. Une fois que tu affiches les events tu vois plus que ca grace a un commit que ca a changé
