### ISSUE TITLE
[SEMENCE] : Ajouter une date de péremption des graines

### ISSUE THREAD

**Issue by neobast** [neobast/potager#57]
Je me suis apercu que les sachets avaient des dates de péremption.
Ne serait il pas judicieux d'inscrire ces dates en base ?

**Comment by magictex33** [comment]
Du coup ca ferait un champ supplémentaire pour le stock ? Quid de plusieurs sachets avec des dates différentes ?

**Comment by neobast** [comment]
Oui un champ optionnel.
Je n'ai pas eu le cas de plusieurs sachets avec des dates différentes. A préciser pour une prise en compte en v1.2 ?
