### ISSUE TITLE
[Feature] Journal de bord

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#62]
Il serait intéressant d'avoir une page récapitulant toutes les actions passées, triées par ordre chronologique inverse.
Les champs seraient suivants :
- Date
 - Parcelle
 - Action - Étape semis - Remarque ou photo miniature

**Comment by neobast** [comment]
Remontée du PO sur la lenteur de l'affichage.
Il faut créer des miniatures pour permettre un affichage plus rapide. 
https://blog.silarhi.fr/symfony-miniature-image-glide-php/

**Comment by magictex33** [comment]
Ok
