### ISSUE TITLE
[SEMENCE] : Ajouter temperature de germination

### ISSUE THREAD

**Issue by neobast** [neobast/potager#65]
Besoin d'avoir la temperature de germination de la graine.
Cela permettra dans le futur de pouvoir le coupler avec un service de météo

**Comment by magictex33** [comment]
+1
Idéalement peut-on le faire passer dans la 1.0 ?

**Comment by magictex33** [comment]
Je ne vois pas où se trouve le champ. Quel modal stp ?

**Comment by neobast** [comment]
Corrigé pour avoir T° germination dans la modale

**Comment by magictex33** [comment]
Top
