### ISSUE TITLE
[STOCK][PEREMPTION][1/3] : Afficher un panneau si date de péremption arrive

### ISSUE THREAD

**Issue by neobast** [neobast/potager#69]
Le but de l'appli est de faire en sorte qu'on soit pas surpris.
Donc si la date de péremption est proche, prévoir un affichage sur l'affichage de la ligne au niveau de l'index

**Comment by neobast** [comment]
Exemple sur le stock index de tom

**Comment by magictex33** [comment]
Super. Je cloture.
