### ISSUE TITLE
[SEMENCE][SHOW] : Modification affichage

### ISSUE THREAD

**Issue by neobast** [neobast/potager#73]
Il faur revoir l'affichage : 
- la lévée
- besoin d'eau ou pas ?
- affichage en nombre de semaines

**Comment by neobast** [comment]
Besoin d'enregistrer le nombre de semaines apres semis pour récolte (pour la planification)

**Comment by neobast** [comment]
@magictex33 Modification à faire au niveau de la semence ou de la plante ? Moi j'aurai tendance à la faire sur la plante.
Ex : courgette : 6 semaines avant récolte (qq soit la variété)

**Comment by neobast** [comment]
Levée : on pourrait dire pareil. C'est sur la plante. Exemple : levée de 5 à 10

**Comment by magictex33** [comment]
Ok pour moi et les éléments sont pris en compte dans la planification.
