### ISSUE TITLE
[Semis] Couleur des labels

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#77]
Il serait intéressant d'affecter un label en fonction de la catégorie d'un état. Idéalment en reprenant ce qui se fait déjà :
- bleu semis
- jaune actions de repiquage etc
- rouge remarques etc
- vert récolte etc

D'une manière plus générique, pourquoi ne pas associer la couleur à l'état via une conf

**Comment by neobast** [comment]
Une couleur par état, c'est pas mal.
Facile à mettre en oeuvre.

**Comment by neobast** [comment]
etatsemis/index

**Comment by magictex33** [comment]
Très bien le fonctionnement pour choisir la couleur. Très classe ! 
Par contre ce n'est pas encore en place pour les états d'un semis n'est ce pas ?

**Comment by neobast** [comment]
Nope. C en cours

**Comment by neobast** [comment]
potager/history

**Comment by neobast** [comment]
Le pb réside sur la couleur de la police a utilisé du coup..

**Comment by neobast** [comment]
Concernant l'affichage, tu souhaites quoi ? un badge boostrap avec la couleur définie avec l'abreviation à l'intérieur ? 
Ou juste un label de couledur ? 
Ou alors la ligne du tableau avec la couleur.. mais la encore pb de couleur de police si on prend des coeleurs trop foncés

**Comment by magictex33** [comment]
Badge de couleur.
Après je pense qu'il doit exister des algos pour la couleur de la police

`// See: http://stackoverflow.com/a/1855903/186965

var c = document.getElementById('container');

var colourIsLight = function (r, g, b) {
  
  // Counting the perceptive luminance
  // human eye favors green color... 
  var a = 1 - (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  console.log(a);
  return (a < 0.5);
}

var randomRgb = function () {
  var r = Math.floor(Math.random() * 256);
  var g = Math.floor(Math.random() * 256);
  var b = Math.floor(Math.random() * 256);
  return [r, g, b];
};

var colourFromRgb = function (r, g, b) {
  return 'rgb(' + r + ',' + g + ',' + b + ')';
};

for (var i = 0; i < 1000; i += 1) {
  var el = document.createElement('div');
  el.setAttribute('class', 'box');
  el.textContent = "Hello";
  
  var bgRgb = randomRgb();
  var bgColour = colourFromRgb(bgRgb[0], bgRgb[1], bgRgb[2]);
  var textColour = colourIsLight(bgRgb[0], bgRgb[1], bgRgb[2]) ? 'black' : 'white';
  
  el.setAttribute('style', 'background-color: ' + bgColour + '; color: ' + textColour);
  
  c.appendChild(el);
}`

**Comment by neobast** [comment]
Par contre, c'est général à toute l'appli. 
Viens de m'en rendre compte.
Je suggére qu'une fois qu'on ai validé, on laisse que les admins le faire ? 
Ou alors, c'est par user mais c une autre story dans ce cas  ;-)

**Comment by magictex33** [comment]
Super comme ca. Je cloture.
