### ISSUE TITLE
[Semis] Titre lors de l'affichage du détail

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#83]
Lors de l'affichage du détail d'un semis, le titre gris ne se détache pas assez du fond. Le changer vers une couleur plus adéquate (#444 vers #FFF ?)

**Comment by neobast** [comment]
Ca te va comme cela ?

**Comment by magictex33** [comment]
Je ne vois pas de différence  (sur mobile pour le moment)

**Comment by magictex33** [comment]
Exemple 

![Screenshot_20200903-090203-01.jpeg](https://user-images.githubusercontent.com/67335206/92082000-3eba6f80-edc4-11ea-9d46-3308f9115fa7.jpeg)

**Comment by neobast** [comment]
Arf.. oui c la couleur des liens une fois qu'on a cliqué dessus... faut que je trouve une autre couleur

**Comment by neobast** [comment]
et là ?

**Comment by neobast** [comment]
http://90.3.181.176/semence/show/107

**Comment by magictex33** [comment]
Parfait !
