### ISSUE TITLE
[Semence] Identifier le rédacteur

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#84]
Il peut s'avérer judicieux de pouvoir identifier le rédacteur d'une fiche Semence si besoin. Ex. semence/show/23 => l'ai-je mal rentrée ou alors appartient-elle à qqun d'autre.
Je propose de faire apparaître cette information dans l'affichage du détail.

**Comment by neobast** [comment]
Concernant l'affichage, je l'ai mis comme ca. IL faudra de toute facon revoir l'affichage pour tout.

**Comment by magictex33** [comment]
Je vois la date de màj, pas qui l'a fait. JAi loupé un truc ?

**Comment by neobast** [comment]
Non no, c'est juste que la colonne est null. je n'ai pas mis de valeur par défaut.

**Comment by magictex33** [comment]
Ah oui, je ne l'avais pas. Supir comme ca, je cloture.
