### ISSUE TITLE
[Historique] Groupage et affichage de la photo seulement si elle existe

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#86]
Lors de l'ffichage de l'historique, un emplacement est systématiquement présent pour chaque date et semis.
Je propose de grouper les éléments par date et d'afficher la photo uniquement si elle existe.

**Comment by neobast** [comment]
Ok. Mais en mode tableau du coup ?

**Comment by magictex33** [comment]
Tableau un peu amélioré 🙄

**Comment by magictex33** [comment]
Le premier tri serait sur le jour, ensuite sur les étapes :
- 25/08/2020
 - Agastache - A - Remarque - Photo
 - Mais - R - Remarque - Photo

**Comment by magictex33** [comment]
Top moumoute !
