### ISSUE TITLE
[Étapes semis] Erreur dans le tri

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#90]
Lors de l'affichage du détail d'un semis - /semis/show/36 - les éléments ne s'affichert pas par date. C'est le seul à priori qui à ce fonctionnement.

![Screenshot_20200903-222341.png](https://user-images.githubusercontent.com/67335206/92163789-8aa4fd00-ee34-11ea-9db9-9352bbfbbe7e.png)

**Comment by neobast** [comment]
Classement par dateaction (avant c tait par état)

**Comment by magictex33** [comment]
Ok.pour moi
