### ISSUE TITLE
Champ exposition - Semence

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#91]
Je me posais la question sur le champ exposition qui est rattaché à la plante.
- Vu qu'une plante comprend plusieurs variétés
- Vu qu'une variété peut avoir des besoins spécifiques

Pourquoi ne rattache-t-on pas le champ exposition à la semence ?

**Comment by neobast** [comment]
Tout à fait

**Comment by magictex33** [comment]
Oui.
Exemple pour les géraniums. Certains sont des plantes d.ombre, d.autres non.

**Comment by magictex33** [comment]
Ok
