### ISSUE TITLE
[Semence] Ajout paramètre nbre-graines/gramme

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#92]
Il est intéressant, pour les variétés à petites graines, de connaitre le nombre de graines au gramme. Ainsi avec le poids des graines, on peut avoir une approximation du nombre de graines présentes dans un sachet.

Ce paramètre pourrait etre positionnéau niveau du paramètre concernant la température de germination

**Comment by magictex33** [comment]
Ok pour la valeur. Par contre pour cloturer l'issue je pense qu'il faudrait ajouter la valeur "Approx. graines" dans le stock.
Cette valeur existerait si la valeur du stock est en grammes et.serait : poids stock x graines/gramme.
Par contre il faudrait alors pouvoir saisir un nombre décimal comme valeur dans le stock.

**Comment by neobast** [comment]
Reçu

**Comment by neobast** [comment]
Vue modifiée au niveau de l'affichage des stocks.

**Comment by magictex33** [comment]
Ok. Par contre faut passer la valeur possible en décimal ou double je pense.
![Screenshot_20200919-150840.png](https://user-images.githubusercontent.com/67335206/93668039-4c414c00-fa8a-11ea-9967-00397f9e1d1e.png)

**Comment by magictex33** [comment]
OK pour la mise à jour. Par contre pour l'affichage de la liste du stock, je pense que tu n'affiches que des entiers.
Exemple pour la Sam Marzano (le poids a été mis à 0.25g) : 
Tomate - San Marzano | 0 g  ~ 200 | €2.50 | LTO061

**Comment by magictex33** [comment]
Ok pour moi.
Avant de cloturer, est il possible d'afficher les chiffres après la virgule seulement quand ils sont différents de zéro.
Ex :
- 200g => 200 g (actuellement 200.00)
- 120.25 => 120.25 g
