### ISSUE TITLE
[STOCK] : doit on garder un historique ? 

### ISSUE THREAD

**Issue by neobast** [neobast/potager#94]
Exemple : j'ai planté toutes les graines d'un sachet d'ail des ours de Tarpin et Charvet.
Mon stock est nul de fait. 

Donc soit je met la quantité à 0 (et il disparait de l'affichage)
Soit je supprime la ligne de stock . 

Je n'arrive pas à trancher. 
Demande d'avis du coup.

**Comment by magictex33** [comment]
Je pense qu'il serait intéressant de rajouter un bouton ou onglet pour filtrer.
- par défaut dans la page je n'affiche que le stock positif
- avec un bouton j'affiche mon stock.nul

**Comment by magictex33** [comment]
Très sympa le nouveau menu ! Je cloture.
