### ISSUE TITLE
[PLANIFICATION] Fonctionnalité planification des cultures

### ISSUE THREAD

**Issue by neobast** [neobast/potager#97]
Epic planification des cultures.
Avant chaque début de saison, cette fonctionnalité permettra de planifier la date des différentes cultures et leur destination.

**Comment by neobast** [comment]
@magictex33 Qu'est ce qu'on avait dit ? me souviens plus....

**Comment by magictex33** [comment]
Regarde les autres issues

**Comment by magictex33** [comment]
Toutes les issues correspondantes à l'epic ont été faites. Je cloture.
Je cloture le milestone aussi. Well done !
