### ISSUE TITLE
[Planification] Ordre d'affichage des états semis

### ISSUE THREAD

**Issue by neobast** [neobast/potager#98]
Ajouter un champ pesmettant de jouer sur l.ordre d.affichage dans le tableau des planefecations

**Comment by neobast** [comment]
Pour l'instant, les semis sont classés par ordre croissant de date.
A quel niveau est ce que je rajoute cet ordre ? au niveau du semis ? 
A priori je dirai ca mais je suis pas sur

**Comment by magictex33** [comment]
Le but étant de voir l'occupation des planches, je pense qu'un tri sur la date max croissante (date de.fin de récolte) serait bien.

**Comment by neobast** [comment]
HUm.. Doublon avec l'affichage label ? https://github.com/neobast/potager/issues/105 ?

**Comment by magictex33** [comment]
Oui. Doublon. Je cloture.
