### ISSUE TITLE
[Planification] Affichage en tableau

### ISSUE THREAD

**Issue by magictex33** [neobast/potager#99]
Sur une meme page, mais pour chaque parcelle, afficher la planification des semis associés avec un ordre spécifique.
La représentation, avec des couleurs, permettra la représentation des différentes phases dans l'occupation de la planche :
- semis
- phase de croissance
- phase de récolte

Question : quid des semis en godet qui seront ensuite transplantés ?

**Comment by neobast** [comment]
@magictex33 vu

**Comment by neobast** [comment]
#73

**Comment by neobast** [comment]
Ajout de paramètres : 

- [ ] nb semaine avant récolte
- [ ] levée mini
- [ ] levée maxi

**Comment by neobast** [comment]
Bon je viens de rajouter l'état prévision dans la base. 
Je sais qu'on a dit des trucs ce maitn, mais me souvien plus.. pfff... 
Ca concerne la levée de mémoire. Je reprends l'exemple des aurora. Peux tu m'aider à me souvenir de ce qu'il fallait que je renomme ou rajoute ?

**Comment by neobast** [comment]
http://potager.ddns.net/planification

**Comment by magictex33** [comment]
On fait un pount demain. Élément que j'ai complètement zappé : la possibilité de faire une rétro planif. En gros : je veux une récolte en semaine n, le semis doit etre fait en semaine n'
J'ouvre l'issue demain.

**Comment by magictex33** [comment]
Oui, en général c'est ca l'idée. Je te propose d'affichir un remplissaqe de couleur pour la semaine du semis et celle de croissance.

On fera un PE pour clarifier comment on représentera le semis en plaques et le transplant ensuite.

**Comment by magictex33** [comment]
OK pour moi, reste le temps en pépinière mais cela fait l'objet de la #110
